### ISSUE TITLE
函数服务部署成功后，通过APIGW开放域名访问。

### ISSUE THREAD

**Issue by 473845166** [ch0ngsheng/openapi-scf-proxy-go#2]
步骤能教一下吗

**Comment by ch0ngsheng** [comment]
操作步骤可以参考[这里](https://github.com/Ice-Hazymoon/openai-scf-proxy/blob/master/README-aliyun.md)

注意，如果使用[本仓库提供的zip包](https://github.com/ch0ngsheng/openapi-scf-proxy-go/releases/tag/v1.3)，务必在云函数`函数配置`里添加并设置`TargetHostURL`和`ProxyListenOn`两个环境变量。

这里的APIGW开放域名，指的是云函数的公网访问地址。
